import { Context } from '../context';
import { GraphQLScalarType } from 'graphql';
export declare const resolvers: {
    DateTime: GraphQLScalarType<Date | null, any>;
    BigInt: GraphQLScalarType<bigint | null, any>;
    Query: {
        users: (_: any, { limit, offset }: {
            limit: number;
            offset: number;
        }, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            sortable_name: string | null;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            avatar_image_url: string | null;
            avatar_image_source: string | null;
            avatar_image_updated_at: Date | null;
            phone: string | null;
            school_name: string | null;
            school_position: string | null;
            short_name: string | null;
            deleted_at: Date | null;
            show_user_services: boolean | null;
            reminder_time_for_due_dates: number | null;
            reminder_time_for_grading: number | null;
            storage_quota: bigint | null;
            visible_inbox_types: string | null;
            subscribe_to_emails: boolean | null;
            features_used: string | null;
            preferences: string | null;
            avatar_state: string | null;
            locale: string | null;
            browser_locale: string | null;
            unread_conversations_count: number | null;
            stuck_sis_fields: string | null;
            public: boolean | null;
            otp_secret_key_enc: string | null;
            otp_secret_key_salt: string | null;
            otp_communication_channel_id: bigint | null;
            initial_enrollment_type: string | null;
            crocodoc_id: number | null;
            last_logged_out: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            lti_id: string | null;
            pronouns: string | null;
            root_account_ids: bigint[];
            merged_into_user_id: bigint | null;
            instructure_identity_id: string | null;
        }[]>;
        user: (_: any, { id }: {
            id: bigint;
        }, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            sortable_name: string | null;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            avatar_image_url: string | null;
            avatar_image_source: string | null;
            avatar_image_updated_at: Date | null;
            phone: string | null;
            school_name: string | null;
            school_position: string | null;
            short_name: string | null;
            deleted_at: Date | null;
            show_user_services: boolean | null;
            reminder_time_for_due_dates: number | null;
            reminder_time_for_grading: number | null;
            storage_quota: bigint | null;
            visible_inbox_types: string | null;
            subscribe_to_emails: boolean | null;
            features_used: string | null;
            preferences: string | null;
            avatar_state: string | null;
            locale: string | null;
            browser_locale: string | null;
            unread_conversations_count: number | null;
            stuck_sis_fields: string | null;
            public: boolean | null;
            otp_secret_key_enc: string | null;
            otp_secret_key_salt: string | null;
            otp_communication_channel_id: bigint | null;
            initial_enrollment_type: string | null;
            crocodoc_id: number | null;
            last_logged_out: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            lti_id: string | null;
            pronouns: string | null;
            root_account_ids: bigint[];
            merged_into_user_id: bigint | null;
            instructure_identity_id: string | null;
        } | null>;
        courses: (_: any, { limit, offset }: {
            limit: number;
            offset: number;
        }, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            storage_quota: bigint | null;
            locale: string | null;
            stuck_sis_fields: string | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            account_id: bigint;
            group_weighting_scheme: string | null;
            start_at: Date | null;
            conclude_at: Date | null;
            grading_standard_id: bigint | null;
            is_public: boolean | null;
            allow_student_wiki_edits: boolean | null;
            show_public_context_messages: boolean | null;
            syllabus_body: string | null;
            allow_student_forum_attachments: boolean | null;
            default_wiki_editing_roles: string | null;
            wiki_id: bigint | null;
            allow_student_organized_groups: boolean | null;
            course_code: string | null;
            default_view: string | null;
            abstract_course_id: bigint | null;
            root_account_id: bigint;
            enrollment_term_id: bigint;
            sis_source_id: string | null;
            sis_batch_id: bigint | null;
            open_enrollment: boolean | null;
            tab_configuration: string | null;
            allow_wiki_comments: boolean | null;
            turnitin_comments: string | null;
            self_enrollment: boolean | null;
            license: string | null;
            indexed: boolean | null;
            restrict_enrollments_to_course_dates: boolean | null;
            template_course_id: bigint | null;
            settings: string | null;
            replacement_course_id: bigint | null;
            public_description: string | null;
            self_enrollment_code: string | null;
            self_enrollment_limit: number | null;
            integration_id: string | null;
            show_announcements_on_home_page: boolean | null;
            home_page_announcement_limit: number | null;
            latest_outcome_import_id: bigint | null;
            grade_passback_setting: string | null;
            template: boolean;
            homeroom_course: boolean;
            sync_enrollments_from_homeroom: boolean;
            homeroom_course_id: bigint | null;
            archived_at: Date | null;
            horizon_course: boolean;
            content_library: boolean;
        }[]>;
        course: (_: any, { id }: {
            id: bigint;
        }, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            storage_quota: bigint | null;
            locale: string | null;
            stuck_sis_fields: string | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            account_id: bigint;
            group_weighting_scheme: string | null;
            start_at: Date | null;
            conclude_at: Date | null;
            grading_standard_id: bigint | null;
            is_public: boolean | null;
            allow_student_wiki_edits: boolean | null;
            show_public_context_messages: boolean | null;
            syllabus_body: string | null;
            allow_student_forum_attachments: boolean | null;
            default_wiki_editing_roles: string | null;
            wiki_id: bigint | null;
            allow_student_organized_groups: boolean | null;
            course_code: string | null;
            default_view: string | null;
            abstract_course_id: bigint | null;
            root_account_id: bigint;
            enrollment_term_id: bigint;
            sis_source_id: string | null;
            sis_batch_id: bigint | null;
            open_enrollment: boolean | null;
            tab_configuration: string | null;
            allow_wiki_comments: boolean | null;
            turnitin_comments: string | null;
            self_enrollment: boolean | null;
            license: string | null;
            indexed: boolean | null;
            restrict_enrollments_to_course_dates: boolean | null;
            template_course_id: bigint | null;
            settings: string | null;
            replacement_course_id: bigint | null;
            public_description: string | null;
            self_enrollment_code: string | null;
            self_enrollment_limit: number | null;
            integration_id: string | null;
            show_announcements_on_home_page: boolean | null;
            home_page_announcement_limit: number | null;
            latest_outcome_import_id: bigint | null;
            grade_passback_setting: string | null;
            template: boolean;
            homeroom_course: boolean;
            sync_enrollments_from_homeroom: boolean;
            homeroom_course_id: bigint | null;
            archived_at: Date | null;
            horizon_course: boolean;
            content_library: boolean;
        } | null>;
        assignments: (_: any, { courseId, limit, offset }: {
            courseId?: bigint;
            limit: number;
            offset: number;
        }, { prisma }: Context) => Promise<{
            description: string | null;
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            grading_standard_id: bigint | null;
            root_account_id: bigint;
            sis_source_id: string | null;
            settings: import("@prisma/client/runtime/library").JsonValue | null;
            integration_id: string | null;
            title: string | null;
            due_at: Date | null;
            unlock_at: Date | null;
            lock_at: Date | null;
            points_possible: number | null;
            min_score: number | null;
            max_score: number | null;
            mastery_score: number | null;
            grading_type: string | null;
            submission_types: string | null;
            context_id: bigint;
            context_type: string;
            assignment_group_id: bigint | null;
            submissions_downloads: number | null;
            peer_review_count: number | null;
            peer_reviews_due_at: Date | null;
            peer_reviews_assigned: boolean;
            peer_reviews: boolean;
            automatic_peer_reviews: boolean;
            all_day: boolean;
            all_day_date: Date | null;
            could_be_locked: boolean;
            cloned_item_id: bigint | null;
            position: number | null;
            migration_id: string | null;
            grade_group_students_individually: boolean;
            anonymous_peer_reviews: boolean;
            time_zone_edited: string | null;
            turnitin_enabled: boolean;
            allowed_extensions: string | null;
            turnitin_settings: string | null;
            muted: boolean;
            group_category_id: bigint | null;
            freeze_on_copy: boolean;
            copied: boolean;
            only_visible_to_overrides: boolean;
            post_to_sis: boolean;
            integration_data: string | null;
            moderated_grading: boolean;
            grades_published_at: Date | null;
            omit_from_final_grade: boolean;
            vericite_enabled: boolean;
            intra_group_peer_reviews: boolean;
            anonymous_instructor_annotations: boolean;
            duplicate_of_id: bigint | null;
            anonymous_grading: boolean | null;
            graders_anonymous_to_graders: boolean | null;
            grader_count: number | null;
            grader_comments_visible_to_graders: boolean | null;
            grader_section_id: bigint | null;
            final_grader_id: bigint | null;
            grader_names_visible_to_final_grader: boolean | null;
            duplication_started_at: Date | null;
            importing_started_at: Date | null;
            allowed_attempts: number | null;
            migrate_from_id: bigint | null;
            annotatable_attachment_id: bigint | null;
            important_dates: boolean;
            hide_in_gradebook: boolean;
            ab_guid: string[];
            parent_assignment_id: bigint | null;
            type: string;
            sub_assignment_tag: string | null;
            has_sub_assignments: boolean;
            rubric_self_assessment_enabled: boolean;
            suppress_assignment: boolean;
        }[]>;
        assignment: (_: any, { id }: {
            id: bigint;
        }, { prisma }: Context) => Promise<{
            description: string | null;
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            grading_standard_id: bigint | null;
            root_account_id: bigint;
            sis_source_id: string | null;
            settings: import("@prisma/client/runtime/library").JsonValue | null;
            integration_id: string | null;
            title: string | null;
            due_at: Date | null;
            unlock_at: Date | null;
            lock_at: Date | null;
            points_possible: number | null;
            min_score: number | null;
            max_score: number | null;
            mastery_score: number | null;
            grading_type: string | null;
            submission_types: string | null;
            context_id: bigint;
            context_type: string;
            assignment_group_id: bigint | null;
            submissions_downloads: number | null;
            peer_review_count: number | null;
            peer_reviews_due_at: Date | null;
            peer_reviews_assigned: boolean;
            peer_reviews: boolean;
            automatic_peer_reviews: boolean;
            all_day: boolean;
            all_day_date: Date | null;
            could_be_locked: boolean;
            cloned_item_id: bigint | null;
            position: number | null;
            migration_id: string | null;
            grade_group_students_individually: boolean;
            anonymous_peer_reviews: boolean;
            time_zone_edited: string | null;
            turnitin_enabled: boolean;
            allowed_extensions: string | null;
            turnitin_settings: string | null;
            muted: boolean;
            group_category_id: bigint | null;
            freeze_on_copy: boolean;
            copied: boolean;
            only_visible_to_overrides: boolean;
            post_to_sis: boolean;
            integration_data: string | null;
            moderated_grading: boolean;
            grades_published_at: Date | null;
            omit_from_final_grade: boolean;
            vericite_enabled: boolean;
            intra_group_peer_reviews: boolean;
            anonymous_instructor_annotations: boolean;
            duplicate_of_id: bigint | null;
            anonymous_grading: boolean | null;
            graders_anonymous_to_graders: boolean | null;
            grader_count: number | null;
            grader_comments_visible_to_graders: boolean | null;
            grader_section_id: bigint | null;
            final_grader_id: bigint | null;
            grader_names_visible_to_final_grader: boolean | null;
            duplication_started_at: Date | null;
            importing_started_at: Date | null;
            allowed_attempts: number | null;
            migrate_from_id: bigint | null;
            annotatable_attachment_id: bigint | null;
            important_dates: boolean;
            hide_in_gradebook: boolean;
            ab_guid: string[];
            parent_assignment_id: bigint | null;
            type: string;
            sub_assignment_tag: string | null;
            has_sub_assignments: boolean;
            rubric_self_assessment_enabled: boolean;
            suppress_assignment: boolean;
        } | null>;
        enrollments: (_: any, { courseId, userId, limit, offset }: {
            courseId?: bigint;
            userId?: bigint;
            limit: number;
            offset: number;
        }, { prisma }: Context) => Promise<{
            id: bigint;
            workflow_state: string;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            stuck_sis_fields: string | null;
            start_at: Date | null;
            root_account_id: bigint;
            sis_batch_id: bigint | null;
            archived_at: Date | null;
            type: string;
            user_id: bigint;
            course_id: bigint;
            associated_user_id: bigint | null;
            end_at: Date | null;
            course_section_id: bigint;
            completed_at: Date | null;
            self_enrolled: boolean | null;
            grade_publishing_status: string | null;
            last_publish_attempt_at: Date | null;
            grade_publishing_message: string | null;
            limit_privileges_to_course_section: boolean;
            last_activity_at: Date | null;
            total_activity_time: number | null;
            role_id: bigint;
            sis_pseudonym_id: bigint | null;
            last_attended_at: Date | null;
            temporary_enrollment_source_user_id: bigint | null;
            temporary_enrollment_pairing_id: bigint | null;
        }[]>;
        submissions: (_: any, { assignmentId, userId, limit, offset }: {
            assignmentId?: bigint;
            userId?: bigint;
            limit: number;
            offset: number;
        }, { prisma }: Context) => Promise<{
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_id: string | null;
            root_account_id: bigint | null;
            user_id: bigint;
            course_id: bigint;
            body: string | null;
            url: string | null;
            attachment_id: bigint | null;
            grade: string | null;
            score: number | null;
            submitted_at: Date | null;
            assignment_id: bigint;
            submission_type: string | null;
            group_id: bigint | null;
            attachment_ids: string | null;
            processed: boolean | null;
            grade_matches_current_submission: boolean | null;
            published_score: number | null;
            published_grade: string | null;
            graded_at: Date | null;
            student_entered_score: number | null;
            grader_id: bigint | null;
            media_comment_id: string | null;
            media_comment_type: string | null;
            quiz_submission_id: bigint | null;
            submission_comments_count: number | null;
            attempt: number | null;
            media_object_id: bigint | null;
            turnitin_data: string | null;
            cached_due_date: Date | null;
            excused: boolean | null;
            graded_anonymously: boolean | null;
            late_policy_status: string | null;
            points_deducted: import("@prisma/client/runtime/library").Decimal | null;
            grading_period_id: bigint | null;
            seconds_late_override: bigint | null;
            lti_user_id: string | null;
            anonymous_id: string | null;
            last_comment_at: Date | null;
            extra_attempts: number | null;
            posted_at: Date | null;
            cached_quiz_lti: boolean;
            cached_tardiness: string | null;
            redo_request: boolean;
            resource_link_lookup_uuid: string | null;
            proxy_submitter_id: bigint | null;
            custom_grade_status_id: bigint | null;
            sticker: string | null;
            body_word_count: number | null;
        }[]>;
        dashboardStats: (_: any, __: any, { prisma }: Context) => Promise<{
            totalUsers: number;
            totalCourses: number;
            totalAssignments: number;
            totalSubmissions: number;
            activeUsers: number;
            activeCourses: number;
        }>;
        courseAnalytics: (_: any, { courseId }: {
            courseId: bigint;
        }, { prisma }: Context) => Promise<{
            courseId: bigint;
            studentEngagement: number;
            averageGrade: any;
            submissionRate: number;
            activityTrend: never[];
        }>;
        searchUsers: (_: any, { query }: {
            query: string;
        }, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            sortable_name: string | null;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            avatar_image_url: string | null;
            avatar_image_source: string | null;
            avatar_image_updated_at: Date | null;
            phone: string | null;
            school_name: string | null;
            school_position: string | null;
            short_name: string | null;
            deleted_at: Date | null;
            show_user_services: boolean | null;
            reminder_time_for_due_dates: number | null;
            reminder_time_for_grading: number | null;
            storage_quota: bigint | null;
            visible_inbox_types: string | null;
            subscribe_to_emails: boolean | null;
            features_used: string | null;
            preferences: string | null;
            avatar_state: string | null;
            locale: string | null;
            browser_locale: string | null;
            unread_conversations_count: number | null;
            stuck_sis_fields: string | null;
            public: boolean | null;
            otp_secret_key_enc: string | null;
            otp_secret_key_salt: string | null;
            otp_communication_channel_id: bigint | null;
            initial_enrollment_type: string | null;
            crocodoc_id: number | null;
            last_logged_out: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            lti_id: string | null;
            pronouns: string | null;
            root_account_ids: bigint[];
            merged_into_user_id: bigint | null;
            instructure_identity_id: string | null;
        }[]>;
        searchCourses: (_: any, { query }: {
            query: string;
        }, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            storage_quota: bigint | null;
            locale: string | null;
            stuck_sis_fields: string | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            account_id: bigint;
            group_weighting_scheme: string | null;
            start_at: Date | null;
            conclude_at: Date | null;
            grading_standard_id: bigint | null;
            is_public: boolean | null;
            allow_student_wiki_edits: boolean | null;
            show_public_context_messages: boolean | null;
            syllabus_body: string | null;
            allow_student_forum_attachments: boolean | null;
            default_wiki_editing_roles: string | null;
            wiki_id: bigint | null;
            allow_student_organized_groups: boolean | null;
            course_code: string | null;
            default_view: string | null;
            abstract_course_id: bigint | null;
            root_account_id: bigint;
            enrollment_term_id: bigint;
            sis_source_id: string | null;
            sis_batch_id: bigint | null;
            open_enrollment: boolean | null;
            tab_configuration: string | null;
            allow_wiki_comments: boolean | null;
            turnitin_comments: string | null;
            self_enrollment: boolean | null;
            license: string | null;
            indexed: boolean | null;
            restrict_enrollments_to_course_dates: boolean | null;
            template_course_id: bigint | null;
            settings: string | null;
            replacement_course_id: bigint | null;
            public_description: string | null;
            self_enrollment_code: string | null;
            self_enrollment_limit: number | null;
            integration_id: string | null;
            show_announcements_on_home_page: boolean | null;
            home_page_announcement_limit: number | null;
            latest_outcome_import_id: bigint | null;
            grade_passback_setting: string | null;
            template: boolean;
            homeroom_course: boolean;
            sync_enrollments_from_homeroom: boolean;
            homeroom_course_id: bigint | null;
            archived_at: Date | null;
            horizon_course: boolean;
            content_library: boolean;
        }[]>;
    };
    User: {
        displayName: (user: any) => any;
        isActive: (user: any) => boolean;
        enrollments: (user: any, _: any, { prisma }: Context) => Promise<{
            id: bigint;
            workflow_state: string;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            stuck_sis_fields: string | null;
            start_at: Date | null;
            root_account_id: bigint;
            sis_batch_id: bigint | null;
            archived_at: Date | null;
            type: string;
            user_id: bigint;
            course_id: bigint;
            associated_user_id: bigint | null;
            end_at: Date | null;
            course_section_id: bigint;
            completed_at: Date | null;
            self_enrolled: boolean | null;
            grade_publishing_status: string | null;
            last_publish_attempt_at: Date | null;
            grade_publishing_message: string | null;
            limit_privileges_to_course_section: boolean;
            last_activity_at: Date | null;
            total_activity_time: number | null;
            role_id: bigint;
            sis_pseudonym_id: bigint | null;
            last_attended_at: Date | null;
            temporary_enrollment_source_user_id: bigint | null;
            temporary_enrollment_pairing_id: bigint | null;
        }[]>;
        submissions: (user: any, _: any, { prisma }: Context) => Promise<{
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_id: string | null;
            root_account_id: bigint | null;
            user_id: bigint;
            course_id: bigint;
            body: string | null;
            url: string | null;
            attachment_id: bigint | null;
            grade: string | null;
            score: number | null;
            submitted_at: Date | null;
            assignment_id: bigint;
            submission_type: string | null;
            group_id: bigint | null;
            attachment_ids: string | null;
            processed: boolean | null;
            grade_matches_current_submission: boolean | null;
            published_score: number | null;
            published_grade: string | null;
            graded_at: Date | null;
            student_entered_score: number | null;
            grader_id: bigint | null;
            media_comment_id: string | null;
            media_comment_type: string | null;
            quiz_submission_id: bigint | null;
            submission_comments_count: number | null;
            attempt: number | null;
            media_object_id: bigint | null;
            turnitin_data: string | null;
            cached_due_date: Date | null;
            excused: boolean | null;
            graded_anonymously: boolean | null;
            late_policy_status: string | null;
            points_deducted: import("@prisma/client/runtime/library").Decimal | null;
            grading_period_id: bigint | null;
            seconds_late_override: bigint | null;
            lti_user_id: string | null;
            anonymous_id: string | null;
            last_comment_at: Date | null;
            extra_attempts: number | null;
            posted_at: Date | null;
            cached_quiz_lti: boolean;
            cached_tardiness: string | null;
            redo_request: boolean;
            resource_link_lookup_uuid: string | null;
            proxy_submitter_id: bigint | null;
            custom_grade_status_id: bigint | null;
            sticker: string | null;
            body_word_count: number | null;
        }[]>;
        courses: (user: any, _: any, { prisma }: Context) => Promise<any[]>;
    };
    Course: {
        isActive: (course: any) => boolean;
        isPublished: (course: any) => boolean;
        studentCount: (course: any, _: any, { prisma }: Context) => Promise<number>;
        teacherCount: (course: any, _: any, { prisma }: Context) => Promise<number>;
        assignmentCount: (course: any, _: any, { prisma }: Context) => Promise<number>;
        enrollments: (course: any, _: any, { prisma }: Context) => Promise<{
            id: bigint;
            workflow_state: string;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            stuck_sis_fields: string | null;
            start_at: Date | null;
            root_account_id: bigint;
            sis_batch_id: bigint | null;
            archived_at: Date | null;
            type: string;
            user_id: bigint;
            course_id: bigint;
            associated_user_id: bigint | null;
            end_at: Date | null;
            course_section_id: bigint;
            completed_at: Date | null;
            self_enrolled: boolean | null;
            grade_publishing_status: string | null;
            last_publish_attempt_at: Date | null;
            grade_publishing_message: string | null;
            limit_privileges_to_course_section: boolean;
            last_activity_at: Date | null;
            total_activity_time: number | null;
            role_id: bigint;
            sis_pseudonym_id: bigint | null;
            last_attended_at: Date | null;
            temporary_enrollment_source_user_id: bigint | null;
            temporary_enrollment_pairing_id: bigint | null;
        }[]>;
        assignments: (course: any, _: any, { prisma }: Context) => Promise<{
            description: string | null;
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            grading_standard_id: bigint | null;
            root_account_id: bigint;
            sis_source_id: string | null;
            settings: import("@prisma/client/runtime/library").JsonValue | null;
            integration_id: string | null;
            title: string | null;
            due_at: Date | null;
            unlock_at: Date | null;
            lock_at: Date | null;
            points_possible: number | null;
            min_score: number | null;
            max_score: number | null;
            mastery_score: number | null;
            grading_type: string | null;
            submission_types: string | null;
            context_id: bigint;
            context_type: string;
            assignment_group_id: bigint | null;
            submissions_downloads: number | null;
            peer_review_count: number | null;
            peer_reviews_due_at: Date | null;
            peer_reviews_assigned: boolean;
            peer_reviews: boolean;
            automatic_peer_reviews: boolean;
            all_day: boolean;
            all_day_date: Date | null;
            could_be_locked: boolean;
            cloned_item_id: bigint | null;
            position: number | null;
            migration_id: string | null;
            grade_group_students_individually: boolean;
            anonymous_peer_reviews: boolean;
            time_zone_edited: string | null;
            turnitin_enabled: boolean;
            allowed_extensions: string | null;
            turnitin_settings: string | null;
            muted: boolean;
            group_category_id: bigint | null;
            freeze_on_copy: boolean;
            copied: boolean;
            only_visible_to_overrides: boolean;
            post_to_sis: boolean;
            integration_data: string | null;
            moderated_grading: boolean;
            grades_published_at: Date | null;
            omit_from_final_grade: boolean;
            vericite_enabled: boolean;
            intra_group_peer_reviews: boolean;
            anonymous_instructor_annotations: boolean;
            duplicate_of_id: bigint | null;
            anonymous_grading: boolean | null;
            graders_anonymous_to_graders: boolean | null;
            grader_count: number | null;
            grader_comments_visible_to_graders: boolean | null;
            grader_section_id: bigint | null;
            final_grader_id: bigint | null;
            grader_names_visible_to_final_grader: boolean | null;
            duplication_started_at: Date | null;
            importing_started_at: Date | null;
            allowed_attempts: number | null;
            migrate_from_id: bigint | null;
            annotatable_attachment_id: bigint | null;
            important_dates: boolean;
            hide_in_gradebook: boolean;
            ab_guid: string[];
            parent_assignment_id: bigint | null;
            type: string;
            sub_assignment_tag: string | null;
            has_sub_assignments: boolean;
            rubric_self_assessment_enabled: boolean;
            suppress_assignment: boolean;
        }[]>;
        students: (course: any, _: any, { prisma }: Context) => Promise<any[]>;
        teachers: (course: any, _: any, { prisma }: Context) => Promise<any[]>;
    };
    Assignment: {
        isPublished: (assignment: any) => boolean;
        isOverdue: (assignment: any) => any;
        submissionCount: (assignment: any, _: any, { prisma }: Context) => Promise<number>;
        gradedCount: (assignment: any, _: any, { prisma }: Context) => Promise<number>;
        averageScore: (assignment: any, _: any, { prisma }: Context) => Promise<number | null>;
        course: (assignment: any, _: any, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            storage_quota: bigint | null;
            locale: string | null;
            stuck_sis_fields: string | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            account_id: bigint;
            group_weighting_scheme: string | null;
            start_at: Date | null;
            conclude_at: Date | null;
            grading_standard_id: bigint | null;
            is_public: boolean | null;
            allow_student_wiki_edits: boolean | null;
            show_public_context_messages: boolean | null;
            syllabus_body: string | null;
            allow_student_forum_attachments: boolean | null;
            default_wiki_editing_roles: string | null;
            wiki_id: bigint | null;
            allow_student_organized_groups: boolean | null;
            course_code: string | null;
            default_view: string | null;
            abstract_course_id: bigint | null;
            root_account_id: bigint;
            enrollment_term_id: bigint;
            sis_source_id: string | null;
            sis_batch_id: bigint | null;
            open_enrollment: boolean | null;
            tab_configuration: string | null;
            allow_wiki_comments: boolean | null;
            turnitin_comments: string | null;
            self_enrollment: boolean | null;
            license: string | null;
            indexed: boolean | null;
            restrict_enrollments_to_course_dates: boolean | null;
            template_course_id: bigint | null;
            settings: string | null;
            replacement_course_id: bigint | null;
            public_description: string | null;
            self_enrollment_code: string | null;
            self_enrollment_limit: number | null;
            integration_id: string | null;
            show_announcements_on_home_page: boolean | null;
            home_page_announcement_limit: number | null;
            latest_outcome_import_id: bigint | null;
            grade_passback_setting: string | null;
            template: boolean;
            homeroom_course: boolean;
            sync_enrollments_from_homeroom: boolean;
            homeroom_course_id: bigint | null;
            archived_at: Date | null;
            horizon_course: boolean;
            content_library: boolean;
        } | null>;
        submissions: (assignment: any, _: any, { prisma }: Context) => Promise<{
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_id: string | null;
            root_account_id: bigint | null;
            user_id: bigint;
            course_id: bigint;
            body: string | null;
            url: string | null;
            attachment_id: bigint | null;
            grade: string | null;
            score: number | null;
            submitted_at: Date | null;
            assignment_id: bigint;
            submission_type: string | null;
            group_id: bigint | null;
            attachment_ids: string | null;
            processed: boolean | null;
            grade_matches_current_submission: boolean | null;
            published_score: number | null;
            published_grade: string | null;
            graded_at: Date | null;
            student_entered_score: number | null;
            grader_id: bigint | null;
            media_comment_id: string | null;
            media_comment_type: string | null;
            quiz_submission_id: bigint | null;
            submission_comments_count: number | null;
            attempt: number | null;
            media_object_id: bigint | null;
            turnitin_data: string | null;
            cached_due_date: Date | null;
            excused: boolean | null;
            graded_anonymously: boolean | null;
            late_policy_status: string | null;
            points_deducted: import("@prisma/client/runtime/library").Decimal | null;
            grading_period_id: bigint | null;
            seconds_late_override: bigint | null;
            lti_user_id: string | null;
            anonymous_id: string | null;
            last_comment_at: Date | null;
            extra_attempts: number | null;
            posted_at: Date | null;
            cached_quiz_lti: boolean;
            cached_tardiness: string | null;
            redo_request: boolean;
            resource_link_lookup_uuid: string | null;
            proxy_submitter_id: bigint | null;
            custom_grade_status_id: bigint | null;
            sticker: string | null;
            body_word_count: number | null;
        }[]>;
    };
    Enrollment: {
        isActive: (enrollment: any) => boolean;
        isStudent: (enrollment: any) => boolean;
        isTeacher: (enrollment: any) => boolean;
        isTA: (enrollment: any) => boolean;
        user: (enrollment: any, _: any, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            sortable_name: string | null;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            avatar_image_url: string | null;
            avatar_image_source: string | null;
            avatar_image_updated_at: Date | null;
            phone: string | null;
            school_name: string | null;
            school_position: string | null;
            short_name: string | null;
            deleted_at: Date | null;
            show_user_services: boolean | null;
            reminder_time_for_due_dates: number | null;
            reminder_time_for_grading: number | null;
            storage_quota: bigint | null;
            visible_inbox_types: string | null;
            subscribe_to_emails: boolean | null;
            features_used: string | null;
            preferences: string | null;
            avatar_state: string | null;
            locale: string | null;
            browser_locale: string | null;
            unread_conversations_count: number | null;
            stuck_sis_fields: string | null;
            public: boolean | null;
            otp_secret_key_enc: string | null;
            otp_secret_key_salt: string | null;
            otp_communication_channel_id: bigint | null;
            initial_enrollment_type: string | null;
            crocodoc_id: number | null;
            last_logged_out: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            lti_id: string | null;
            pronouns: string | null;
            root_account_ids: bigint[];
            merged_into_user_id: bigint | null;
            instructure_identity_id: string | null;
        } | null>;
        course: (enrollment: any, _: any, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            deleted_at: Date | null;
            storage_quota: bigint | null;
            locale: string | null;
            stuck_sis_fields: string | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            account_id: bigint;
            group_weighting_scheme: string | null;
            start_at: Date | null;
            conclude_at: Date | null;
            grading_standard_id: bigint | null;
            is_public: boolean | null;
            allow_student_wiki_edits: boolean | null;
            show_public_context_messages: boolean | null;
            syllabus_body: string | null;
            allow_student_forum_attachments: boolean | null;
            default_wiki_editing_roles: string | null;
            wiki_id: bigint | null;
            allow_student_organized_groups: boolean | null;
            course_code: string | null;
            default_view: string | null;
            abstract_course_id: bigint | null;
            root_account_id: bigint;
            enrollment_term_id: bigint;
            sis_source_id: string | null;
            sis_batch_id: bigint | null;
            open_enrollment: boolean | null;
            tab_configuration: string | null;
            allow_wiki_comments: boolean | null;
            turnitin_comments: string | null;
            self_enrollment: boolean | null;
            license: string | null;
            indexed: boolean | null;
            restrict_enrollments_to_course_dates: boolean | null;
            template_course_id: bigint | null;
            settings: string | null;
            replacement_course_id: bigint | null;
            public_description: string | null;
            self_enrollment_code: string | null;
            self_enrollment_limit: number | null;
            integration_id: string | null;
            show_announcements_on_home_page: boolean | null;
            home_page_announcement_limit: number | null;
            latest_outcome_import_id: bigint | null;
            grade_passback_setting: string | null;
            template: boolean;
            homeroom_course: boolean;
            sync_enrollments_from_homeroom: boolean;
            homeroom_course_id: bigint | null;
            archived_at: Date | null;
            horizon_course: boolean;
            content_library: boolean;
        } | null>;
    };
    Submission: {
        isSubmitted: (submission: any) => boolean;
        isGraded: (submission: any) => boolean;
        isLate: (submission: any) => boolean;
        assignment: (submission: any, _: any, { prisma }: Context) => Promise<{
            description: string | null;
            id: bigint;
            workflow_state: string;
            created_at: Date | null;
            updated_at: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            grading_standard_id: bigint | null;
            root_account_id: bigint;
            sis_source_id: string | null;
            settings: import("@prisma/client/runtime/library").JsonValue | null;
            integration_id: string | null;
            title: string | null;
            due_at: Date | null;
            unlock_at: Date | null;
            lock_at: Date | null;
            points_possible: number | null;
            min_score: number | null;
            max_score: number | null;
            mastery_score: number | null;
            grading_type: string | null;
            submission_types: string | null;
            context_id: bigint;
            context_type: string;
            assignment_group_id: bigint | null;
            submissions_downloads: number | null;
            peer_review_count: number | null;
            peer_reviews_due_at: Date | null;
            peer_reviews_assigned: boolean;
            peer_reviews: boolean;
            automatic_peer_reviews: boolean;
            all_day: boolean;
            all_day_date: Date | null;
            could_be_locked: boolean;
            cloned_item_id: bigint | null;
            position: number | null;
            migration_id: string | null;
            grade_group_students_individually: boolean;
            anonymous_peer_reviews: boolean;
            time_zone_edited: string | null;
            turnitin_enabled: boolean;
            allowed_extensions: string | null;
            turnitin_settings: string | null;
            muted: boolean;
            group_category_id: bigint | null;
            freeze_on_copy: boolean;
            copied: boolean;
            only_visible_to_overrides: boolean;
            post_to_sis: boolean;
            integration_data: string | null;
            moderated_grading: boolean;
            grades_published_at: Date | null;
            omit_from_final_grade: boolean;
            vericite_enabled: boolean;
            intra_group_peer_reviews: boolean;
            anonymous_instructor_annotations: boolean;
            duplicate_of_id: bigint | null;
            anonymous_grading: boolean | null;
            graders_anonymous_to_graders: boolean | null;
            grader_count: number | null;
            grader_comments_visible_to_graders: boolean | null;
            grader_section_id: bigint | null;
            final_grader_id: bigint | null;
            grader_names_visible_to_final_grader: boolean | null;
            duplication_started_at: Date | null;
            importing_started_at: Date | null;
            allowed_attempts: number | null;
            migrate_from_id: bigint | null;
            annotatable_attachment_id: bigint | null;
            important_dates: boolean;
            hide_in_gradebook: boolean;
            ab_guid: string[];
            parent_assignment_id: bigint | null;
            type: string;
            sub_assignment_tag: string | null;
            has_sub_assignments: boolean;
            rubric_self_assessment_enabled: boolean;
            suppress_assignment: boolean;
        } | null>;
        user: (submission: any, _: any, { prisma }: Context) => Promise<{
            name: string | null;
            id: bigint;
            sortable_name: string | null;
            workflow_state: string;
            time_zone: string | null;
            uuid: string | null;
            created_at: Date;
            updated_at: Date;
            avatar_image_url: string | null;
            avatar_image_source: string | null;
            avatar_image_updated_at: Date | null;
            phone: string | null;
            school_name: string | null;
            school_position: string | null;
            short_name: string | null;
            deleted_at: Date | null;
            show_user_services: boolean | null;
            reminder_time_for_due_dates: number | null;
            reminder_time_for_grading: number | null;
            storage_quota: bigint | null;
            visible_inbox_types: string | null;
            subscribe_to_emails: boolean | null;
            features_used: string | null;
            preferences: string | null;
            avatar_state: string | null;
            locale: string | null;
            browser_locale: string | null;
            unread_conversations_count: number | null;
            stuck_sis_fields: string | null;
            public: boolean | null;
            otp_secret_key_enc: string | null;
            otp_secret_key_salt: string | null;
            otp_communication_channel_id: bigint | null;
            initial_enrollment_type: string | null;
            crocodoc_id: number | null;
            last_logged_out: Date | null;
            lti_context_id: string | null;
            turnitin_id: bigint | null;
            lti_id: string | null;
            pronouns: string | null;
            root_account_ids: bigint[];
            merged_into_user_id: bigint | null;
            instructure_identity_id: string | null;
        } | null>;
    };
};
//# sourceMappingURL=index.d.ts.map